// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar_btn': string;
  'icon_btn': string;
  'slider': string;
  'sound_btn': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
